### ISSUE TITLE
empty space results in valid email

### ISSUE THREAD

**Issue by das-akeem** [iamcal/rfc822#2]
hi,
i tested demo.php (locally) and an email with 
an empty space in it (  test@ test.com ) turns 
out to be valid :(

regards, akeem

**Comment by iamcal** [comment]
This is allowed because of comment-folding whitespace (CFWS) which is allowed in the `domain-literal` and `dot-atom` rules. Whitespace is _not_ allowed in the local part of the address, only the domain.

If you want to disable this behavior, set `$cfws` to the empty string inside the function.
